name: 部署到腾讯云

on:
  push:
    branches:
      - main  # 或者你的默认分支

jobs:
  build-and-deploy:
    runs-on: CentOS 7.6 64bit
    steps:
      # 官方action, 将代码拉取到虚拟机
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: 配置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'v18.19.0'

      - name: 安装依赖
        run: |
          pnpm install

      - name: 构建静态网站
        run: |
          pnpm docs:build

      # 部署到腾讯云服务器
      - name: Upload files to server
        uses: appleboy/scp-action@master
        with:
          # 服务器域名
          host: ${{ secrets.SERVER_HOST }}
          # 服务器用户名
          username: ${{ secrets.SERVER_USERNAME }}
          # 服务器密码
          password: ${{ secrets.SERVER_PASSWORD }}
          # 服务器端口
          port: ${{ secrets.SERVER_PORT }}
          # 指定上传的文件目录(项目配置的打包目录名称)

          source: 'src/.vuepress/dist' # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          target: '/home/lighthouse/my-blog' # 目标目录
          # 解压时覆盖现有文件
          overwrite: true
          # 删除指定数量的前导路径元素
          strip_components: 1
